# .coveralls.yml example configuration

repo_token: 3YEi9TqQ7sM9PgFB4TGEy6R4zuIAm0ZMZ # should be kept secret!
service_name: travis-ci

# for php-coveralls
src_dir: ./
coverage_clover: build/logs/clover.cov
json_path: build/logs/coveralls-upload.json